
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://obbnnsemlblfqmkhqfkk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9iYm5uc2VtbGJsZnFta2hxZmtrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMTExMTEsImV4cCI6MjA1OTc4NzExMX0.T6tg2znGUjLsfTgANPQBhxign7e8XawgbmDGab-txlU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
